# Kyle Stewart.
# File: makefile
# Project: makefile
# Purpose: Contains build instructions for the project
# 5/5/2024.

equakeFunctions.o: equakeFunctions.c
	gcc -c equakeFunctions.c -o equakeFunctions.o

clean:
	rm  -f equakeFunctions.o